### ISSUE TITLE
Aeternity node(s) chart

### ISSUE THREAD

**Issue by dincho** [aeternity/helm-charts#1]
Use cases:
- bootstrap/seed nodes
- API (gateway) nodes
- private network

Functionality
- [ ] [proper health checks/readiness](https://github.com/aeternity/helm-charts/issues/2)
- [ ] [database persistence](https://github.com/aeternity/helm-charts/issues/4)
- [ ] [restore from snapshot](https://github.com/aeternity/helm-charts/issues/5)
- [ ] [p2p connections](https://github.com/aeternity/helm-charts/issues/6)
- [ ] [API nodes](https://github.com/aeternity/helm-charts/issues/7)
- [ ] [static peer keys](https://github.com/aeternity/helm-charts/issues/11)
- [ ] [static IP address](https://github.com/aeternity/helm-charts/issues/12)
- [ ] [multiple nodes](https://github.com/aeternity/helm-charts/issues/9)
- [ ] [Sync based readiness probe](https://github.com/aeternity/helm-charts/issues/10)
